config/routes.rb
Rails.application.routes.draw do
  resources :invoice_items
  resources :invoices
  resources :products
  resources :member_payments
  resources :billing_accounts
  resources :gl_accounts
  resources :trainers
  resources :schedules
  root 'access#menu'
  get 'access/menu'
  get 'access/blog'
  get 'access/week_calendar'
  get 'access/month_calendar'
  get 'reports/gl_accounts_list'
  get 'access/reports/index'
  get 'accounting/reports/index'
  get 'accounting/reports/menu'
  get 'access/registro_miembros'
  namespace :accounting do
    resource :reports
    resource :settings
  end

  namespace :admin do
      resources :users
      resources :gymsites
      resources :members
      resources :trainers
      resources :schedules
      resources :gl_accounts
      resources :account_types
      resources :billing_accounts
      resources :member_payments

      root to: "users#index"
    end

    namespace :settings do
      resources :gl_accounts
      resource :gymsites, only: [:edit, :update]
      # resource :members, only: [:edit, :update], as: 'member'
      resource :users, except: [:show]
  end
  resources :members
   get 'active_members', to: 'members#active_members'
  get 'inactive_members', to: 'members#inactive_members'


  devise_for :users
  resources :gymsites
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/accounting/reports_controller.rb
module Accounting
  class ReportsController < ApplicationController
    def menu
    end 
    def index
      @accounts = GlAccount.all
      respond_to do |format|
        format.html
        format.pdf do
          pdf = ChartPdf.new(@accounts, view_context)
          time = Time.now.to_i
          send_data pdf.render,
          filename: "#{time}_chart_accounts.pdf",
          type: 'application/pdf',
          disposition: 'inline'
        end
      end
    end

    def transactions
      @gl_transactions = GlTransaction.all
      @transaction_details = TransactionDetail.all
      respond_to do |format|
        format.html
        format.pdf do
          pdf = TransactionPdf.new(@gl_transactions, @transaction_details, view_context)
          time = Time.now
          send_data pdf.render,
          filename: "#{time.strftime('%y%m%d')}_Transactions.pdf",
          type: 'application/pdf',
          disposition: 'inline'
        end
      end
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  layout 'application'
end

app/views/accounting/reports/index.html.erb
<div class = 'container-fluid'>
  <div class= 'row'>
    <div class= 'col-sm-3'></div>
    <div class = 'col-sm-6'>
      <h3> Ajustes de la Contabilidad </h3>
      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
      <% end %>

        <table>
        <tr><td><%= link_to 'Editar datos del gimnasio',edit_settings_gymsites_path %></td></tr>
        <tr><td><%= link_to 'Editar las cuentas del Libro Mayor', new_gl_account_path %></td></tr>

          <tr>
            <td><a href="#">Crear el listado de cuentas del mayor - html  <%GlAccountsHelper::create_chart_of_accounts_html%></a></td>
          </tr>
          <tr>
            <td><%=link_to 'Listar las cuentas del libro mayor:formato (html)',reports_gl_accounts_list_path %></td>
          </tr>
          <tr>
              <td><%= link_to "Listar las cuentas del mayor: formato (PDF)", accounting_reports_index_path( format: 'pdf') %></td>
          </tr>

          <tr><td><a href='#'>Edit General Ledger Accounts</a></td></tr>
          <tr><td><a href='#'>Edit General Ledger Accounts</a></td></tr>
      </table>
      </div>
      <div class= 'col-sm-3'></div>
    </div>
  </div>

app/views/accounting/reports/menu.html.erb
<h2> Accounting Reports Menu</h2>
  <h3>views/accounting/reports/menu</h3>