config/routes.rb
Rails.application.routes.draw do
  resources :invoice_items
  resources :invoices
  resources :products
  resources :member_payments
  resources :billing_accounts
  resources :gl_accounts
  resources :trainers
  resources :schedules
  root 'access#menu'
  get 'access/menu'
  get 'access/blog'
  get 'access/week_calendar'
  get 'access/month_calendar'
  get 'reports/gl_accounts_list'
  get 'access/reports/index'
  get 'accounting/reports/index'
  get 'accounting/reports/menu'
  get 'access/registro_miembros'
  namespace :accounting do
    resource :reports
    resource :settings
  end

  namespace :admin do
      resources :users
      resources :gymsites
      resources :members
      resources :trainers
      resources :schedules
      resources :gl_accounts
      resources :account_types
      resources :billing_accounts
      resources :member_payments

      root to: "users#index"
    end

    namespace :settings do
      resources :gl_accounts
      resource :gymsites, only: [:edit, :update]
      # resource :members, only: [:edit, :update], as: 'member'
      resource :users, except: [:show]
  end
  resources :members
   get 'active_members', to: 'members#active_members'
  get 'inactive_members', to: 'members#inactive_members'


  devise_for :users
  resources :gymsites
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gymsite.rb
# == Schema Information
#
# Table name: gymsites
#
#  id             :bigint(8)        not null, primary key
#  name           :string
#  legal_id       :string
#  description    :text
#  street_address :string
#  city           :string
#  state          :string
#  country        :string
#  zip            :string
#  phone          :string
#  phone_type     :integer
#  email          :string
#  logo           :string
#  from_date      :date
#  to_date        :date
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Gymsite < ApplicationRecord
  has_many :members
  has_many :users
  has_many :schedules
  has_many :gl_accounts
  has_many :trainers

end

app/controllers/admin/gymsites_controller.rb
module Admin
  class GymsitesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Gymsite.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Gymsite.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/gymsites_controller.rb
class GymsitesController < ApplicationController
end

app/controllers/settings/gymsites_controller.rb
module Settings
  class GymsitesController < ApplicationController
    before_action :gymsite

    def edit
    end

    def update
      if @gymsite.update_attributes(permitted_params)
        redirect_to accounting_reports_path, flash: {
          success: 'Gym Site was succesfully updated'
        }
      else
        render :edit
      end
    end

  private

    def permitted_params
      params.require(:gymsite).permit(:name, :description, :legal_id, :logo, :street_address, :city, :state, :country, :zip, :email, :phone, :admin_id, :owner_id, :from_date, :to_date)
    end


  end
end

app/helpers/gymsites_helper.rb
module GymsitesHelper
end

app/views/settings/gymsites/edit.html.erb
<div class="panel">
  <div class="panel-heading">
    <h2>Edit Gym Site Settings</h2>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="panel-body">
        <%= form_for @gymsite, url: settings_gymsites_path, html: { class: 'form-settings' } do |f| %>
        <%= render 'layouts/shared/errors', object: @gymsite %>

        <div class="form-group">
          <%= f.label :name, 'Name', class: 'col-lg-6 col-sm-6 control-label' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description, 'Description', class: 'col-lg-6 col-sm-6 control-label' %>
          <%= f.text_field :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone, class: 'col-lg-6 col-sm-6 control-label' %>
          <%= f.text_field :phone, "placeholder data-mask" => "(999) 999-9999", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, class: 'col-lg-6 col-sm-6 control-label' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
      </div>
    </div><!-- end of col -->
    <div class="panel">
      <div class='col-md-6'>
        <div class="panel-body">
        <div class="form-group">
          <%= f.label :street_address, 'Street Address', class: 'col-lg-6 col-sm-6 control-label' %>
          <%= f.text_field :street_address, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :city, class: 'col-lg-6 col-sm-6 control-label' %>
          <%= f.text_field :city, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :state, class: 'col-lg-6 col-sm-6 control-label' %>
          <%= f.text_field :state, class: 'form-control'  %>
        </div>
        <div class="form-group">
          <%= f.label :zip, class: 'col-lg-6 col-sm-6 control-label' %>
          <%= f.text_field :zip, class: 'form-control' %>
        </div>
        <br/>
        <%= f.submit nil, class: 'btn btn-primary' %>
        <% end %>
      </div>
      </div><!-- end of 2nd column -->
    </div>
  </div>
</div>