config/routes.rb
Rails.application.routes.draw do
  resources :invoice_items
  resources :invoices
  resources :products
  resources :member_payments
  resources :billing_accounts
  resources :gl_accounts
  resources :trainers
  resources :schedules
  root 'access#menu'
  get 'access/menu'
  get 'access/blog'
  get 'access/week_calendar'
  get 'access/month_calendar'
  get 'reports/gl_accounts_list'
  get 'access/reports/index'
  get 'accounting/reports/index'
  get 'accounting/reports/menu'
  get 'access/registro_miembros'
  namespace :accounting do
    resource :reports
    resource :settings
  end

  namespace :admin do
      resources :users
      resources :gymsites
      resources :members
      resources :trainers
      resources :schedules
      resources :gl_accounts
      resources :account_types
      resources :billing_accounts
      resources :member_payments

      root to: "users#index"
    end

    namespace :settings do
      resources :gl_accounts
      resource :gymsites, only: [:edit, :update]
      # resource :members, only: [:edit, :update], as: 'member'
      resource :users, except: [:show]
  end
  resources :members
   get 'active_members', to: 'members#active_members'
  get 'inactive_members', to: 'members#inactive_members'


  devise_for :users
  resources :gymsites
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trainer.rb
# == Schema Information
#
# Table name: trainers
#
#  id         :bigint(8)        not null, primary key
#  first_name :string
#  last_name  :string
#  skill      :integer
#  note       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  email      :string
#  gymsite_id :bigint(8)
#

class Trainer < ApplicationRecord
  has_many :schedules
  belongs_to :gymsite
end

app/controllers/admin/trainers_controller.rb
module Admin
  class TrainersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Trainer.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Trainer.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:first_name, :last_name, :skill, :note)
    end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/_form.html.erb
<%= simple_form_for(@trainer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :skill %>
    <%= f.input :note %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Skill</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.first_name %></td>
        <td><%= trainer.last_name %></td>
        <td><%= trainer.skill %></td>
        <td><%= trainer.note %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @trainer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @trainer.last_name %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @trainer.skill %>
</p>

<p>
  <strong>Note:</strong>
  <%= @trainer.note %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>